version: '3.1'

services:
  ndwp:
    build: .
    restart: always
    ports:
      - 12000:80
    env_file:
      - .env.dev
    depends_on:
      - db
    volumes:
      - .:/var/www/html

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env.dev

volumes:
  db_data:
